apiVersion: apps/v1
kind: Deployment
metadata:
  name: fraud-detection-system
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fraud-detection-system
  template:
    metadata:
      labels:
        app: fraud-detection-system
    spec:
      containers:
      - name: fraud-detection-system
        image: ${{ secrets.DOCKER_USERNAME }}/frauddetectionsystem:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi