apiVersion: v1
kind: Service
metadata:
  name: fraud-detection-system
spec:
  selector:
    app: fraud-detection-system
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer