   apiVersion: apps/v1
   kind: Deployment
   metadata:
     name: fraud-detection-system
   spec:
     replicas: 3
     selector:
       matchLabels:
         app: fraud-detection-system
     template:
       metadata:
         labels:
           app: fraud-detection-system
       spec:
         containers:
         - name: fraud-detection-system
           image: ${DOCKER_USERNAME}/fraud-detection-system:${IMAGE_TAG}
           ports:
           - containerPort: 8080
           resources:
             requests:
               cpu: 100m
               memory: 128Mi
             limits:
               cpu: 500m
               memory: 512Mi
           readinessProbe:
             httpGet:
               path: /actuator/health
               port: 8080
             initialDelaySeconds: 30
             periodSeconds: 10
             failureThreshold: 3
             timeoutSeconds: 5
           livenessProbe:
             httpGet:
               path: /actuator/health
               port: 8080
             initialDelaySeconds: 60
             periodSeconds: 15
             failureThreshold: 3
             timeoutSeconds: 5
           env:
           - name: SPRING_PROFILES_ACTIVE
             value: "production"
           - name: JAVA_OPTS
             value: "-Xmx512m -Xms256m"