apiVersion: v1
kind: Service
metadata:
  name: fraud-detection-service
spec:
  selector:
    app: fraud-detection-service
  ports:
    - protocol: TCP
      port: 80        # External port
      targetPort: 8081 # Port on the container
  type: LoadBalancer