apiVersion: v1
kind: Service
metadata:
  name: fraud-detection-system
spec:
  selector:
    app: fraud-detection-system
  ports:
    - protocol: TCP
      port: 80        # External port
      targetPort: 8080 # Port on the container
  type: LoadBalancer