server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/your-repo/config-repo
          clone-on-start: true
  profiles:
    active: native
  application:
    name: config-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/