name: Continuous Deployment

on:
  repository_dispatch:
    types: [trigger-cd]

env:
  KUBERNETES_NAMESPACE: fraud-detection

jobs:
  download-artifact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: FraudDetectionSystem
          path: target
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.client_payload.run_id }}
      - name: Display structure of downloaded files
        run: ls -R target
      - uses: actions/upload-artifact@v4
        with:
          name: FraudDetectionSystem-CD
          path: target/FraudDetectionSystem-1.0-SNAPSHOT.jar
          retention-days: 1

  docker-build-push:
    needs: download-artifact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: FraudDetectionSystem-CD
          path: target
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/fraud-detection-system:latest
            ${{ secrets.DOCKER_USERNAME }}/fraud-detection-system:${{ github.sha }}

  deploy-to-kind:
    needs: docker-build-push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Kind
        run: |
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.20.0/kind-linux-amd64
          chmod +x ./kind
          sudo mv ./kind /usr/local/bin/kind
      - name: Create Kind cluster
        run: kind create cluster
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
      - name: Create namespace
        run: kubectl create namespace ${{ env.KUBERNETES_NAMESPACE }}
      - name: Deploy to Kind
        run: |
          kubectl apply -f k8s/configmap.yaml -n ${{ env.KUBERNETES_NAMESPACE }}
          kubectl apply -f k8s/deployment.yaml -n ${{ env.KUBERNETES_NAMESPACE }}
          kubectl apply -f k8s/service.yaml -n ${{ env.KUBERNETES_NAMESPACE }}
      - name: Wait for deployment
        run: |
          kubectl rollout status deployment/fraud-detection-system -n ${{ env.KUBERNETES_NAMESPACE }} --timeout=300s
      - name: Run tests
        run: |
          echo "Running tests..."
          kubectl get pods -n ${{ env.KUBERNETES_NAMESPACE }}
          kubectl get services -n ${{ env.KUBERNETES_NAMESPACE }}
          kubectl port-forward service/fraud-detection-system 8080:80 -n ${{ env.KUBERNETES_NAMESPACE }} &
          sleep 10
          curl -f http://localhost:8080/health || exit 1

  notify:
    if: failure()
    needs: [download-artifact, docker-build-push, deploy-to-kind]
    runs-on: ubuntu-latest
    steps:
      - name: Send email notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: Build Notification - Failure in ${{ github.workflow }}
          to: henryleungdemotest@gmail.com
          from: github-actions@gmail.com
          body: |
            Build Notification

            The build has failed in the ${{ github.workflow }} workflow.

            Repository: ${{ github.repository }}
            Branch: ${{ github.ref }}
            Commit: ${{ github.sha }}
            Build URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

            Please check the logs for more details.