name: Continuous Deployment

on:
  workflow_run:
    workflows: ["Continuous Integration"]
    types:
      - completed

jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: FraudDetectionSystem
          path: target

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker buildx build --push --tag ${{ secrets.DOCKER_USERNAME }}/fraud-detection-system:latest --tag ${{ secrets.DOCKER_USERNAME }}/fraud-detection-system:${{ github.sha }} .

      - name: Clean up old images
        run: |
          docker image prune -f
          docker images --filter "dangling=true" -q | xargs -r docker rmi

  deploy-to-kind:
    needs: docker-build-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Kind
        run: |
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.20.0/kind-linux-amd64
          chmod +x ./kind
          sudo mv ./kind /usr/local/bin/kind

      - name: Delete existing Kind cluster
        run: kind delete cluster || true

      - name: Create Kind cluster
        run: kind create cluster

      - name: Deploy to Kind
        run: |
          kubectl apply -f k8s/configmap.yaml
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml

      - name: Run tests
        run: |
          # Add your test commands here
          echo "Running tests..."