name: Java CI/CD

on:
  push:
    branches: [ main ]  # Change to 'master' if your default branch is 'master'
  pull_request:
    branches: [ main ]  # Change to 'master' if your default branch is 'master'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build with Maven
      run: mvn clean install -s custom-settings.xml

    - name: Run tests
      run: mvn test

  notify:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Send email notification
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: Build Status
        body: |
          The build process has completed.
          Build Status: ${{ job.status }}
        to: recipient@example.com
        from: ${{ secrets.EMAIL_USERNAME }}