name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Build with Maven
        run: mvn clean install

      - name: List target directory contents
        run: ls -l target/

      - name: List all files in the project directory
        run: find . -type f

      - name: Verify JAR file exists
        run: test -f target/FraudDetectionSystem-1.0-SNAPSHOT.jar && echo "JAR file exists" || echo "JAR file does not exist"

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/frauddetectionsystem:latest .

      - name: Log in to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/frauddetectionsystem:latest

      - name: Install kind
        run: |
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.11.1/kind-linux-amd64
          chmod +x ./kind
          sudo mv ./kind /usr/local/bin/kind

      - name: Create Kubernetes cluster
        run: kind create cluster --wait 5m

      - name: Set up kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'latest'

      - name: Deploy to local Kubernetes cluster
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml

      - name: Run integration tests
        run: mvn verify

      - name: Start application server
        run: |
          nohup java -jar target/FraudDetectionSystem-1.0-SNAPSHOT.jar &

      - name: Wait for server to start
        run: sleep 30

      - name: List tests directory contents
        run: ls -l tests/

      - name: Run end-to-end tests
        run: |
          npm install -g newman
          newman run tests/postman_collection.json

  notify:
    runs-on: ubuntu-latest
    needs: build
    if: failure()
    steps:
      - name: Send email notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: Build Notification
          to: henryleungdemotest@gmail.com
          from: github-actions@gmail.com
          body: |
            Build Notification

            The build has completed successfully.

            **Repository**: ${{ github.repository }}
            **Branch**: ${{ github.ref }}
            **Commit**: ${{ github.sha }}
            **Commit Message**: ${{ github.event.head_commit.message }}
            **Author**: ${{ github.event.head_commit.author.name }}
            **Build URL**: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

            Please check the logs for more details.