name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC

env:
  JAVA_VERSION: '11'
  DOCKER_IMAGE: ${{ secrets.DOCKER_USERNAME }}/frauddetectionsystem

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'adopt'
          cache: maven
      - name: Build and test
        run: |
          mvn -B clean package --file pom.xml -s custom-settings.xml
          mvn test -s custom-settings.xml
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: FraudDetectionSystem
          path: target/FraudDetectionSystem-*.jar

  security-scan:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run OWASP Dependency-Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: 'FraudDetectionSystem'
          path: '.'
          format: 'HTML'
      - name: Upload OWASP Dependency-Check report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: ${{github.workspace}}/reports

  docker-build-push:
    needs: [build-and-test, security-scan]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: FraudDetectionSystem
          path: target
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_IMAGE }}:latest,${{ env.DOCKER_IMAGE }}:${{ github.sha }}
          cache-from: type=registry,ref=${{ env.DOCKER_IMAGE }}:buildcache
          cache-to: type=registry,ref=${{ env.DOCKER_IMAGE }}:buildcache,mode=max

  deploy-local-k8s:
    needs: docker-build-push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Minikube
        uses: medyagh/setup-minikube@master
      - name: Deploy to local Kubernetes
        run: |
          minikube start
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml
          kubectl set image deployment/fraud-detection-system fraud-detection-system=${{ env.DOCKER_IMAGE }}:${{ github.sha }}
      - name: Wait for deployment
        run: |
          echo "Waiting for deployment to be ready..."
          kubectl rollout status deployment/fraud-detection-system --timeout=300s
          echo "Deployment status:"
          kubectl get deployments
          echo "Pod status:"
          kubectl get pods
          echo "Describing pods:"
          kubectl describe pods
      - name: Check service
        run: |
          echo "Checking service status..."
          kubectl get services
          echo "Describing service:"
          kubectl describe service fraud-detection-system
      - name: Wait for service
        run: |
          echo "Waiting for service to be available..."
          timeout 300s bash -c 'while [[ -z $(minikube service fraud-detection-system --url) ]]; do sleep 5; done'
          SERVICE_URL=$(minikube service fraud-detection-system --url)
          echo "Service URL: $SERVICE_URL"
      - name: Test service
        run: |
          SERVICE_URL=$(minikube service fraud-detection-system --url)
          echo "Testing service at $SERVICE_URL"
          curl -v $SERVICE_URL

  integration-tests:
    needs: deploy-local-k8s
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run integration tests
        run: |
          npm install -g newman
          SERVICE_URL=$(minikube service fraud-detection-system --url)
          echo "Running tests against $SERVICE_URL"
          newman run tests/postman_collection.json --env-var "baseUrl=$SERVICE_URL"

  notify:
    if: failure()
    needs: 
      - build-and-test
      - security-scan
      - docker-build-push
      - deploy-local-k8s
      - integration-tests
    runs-on: ubuntu-latest
    steps:
      - name: Send email notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: Build Notification - Failure in ${{ github.workflow }}
          to: henryleungdemotest@gmail.com
          from: github-actions@gmail.com
          body: |
            Build Notification

            The build has failed in the ${{ github.workflow }} workflow.

            **Repository**: ${{ github.repository }}
            **Branch**: ${{ github.ref }}
            **Commit**: ${{ github.sha }}
            **Commit Message**: ${{ github.event.head_commit.message }}
            **Author**: ${{ github.event.head_commit.author.name }}
            **Build URL**: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

            Please check the logs for more details.