name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Updated to the latest version

    - name: Set up JDK 11
      uses: actions/setup-java@v4  # Updated to the latest version
      with:
        distribution: 'adopt'  # Ensure you provide the required input
        java-version: '11'

    - name: Build with Maven
      run: mvn clean install

    - name: Run tests
      run: mvn test

    - name: Verify JAR file exists
      run: ls -l target/FraudDetectionSystem.jar

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/frauddetectionsystem:latest .

    - name: Log in to Docker Hub
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/frauddetectionsystem:latest

    - name: Deploy to Kubernetes
      uses: azure/k8s-deploy@v1
      with:
        manifests: |
          deployment.yaml
          service.yaml
        images: |
          ${{ secrets.DOCKER_USERNAME }}/frauddetectionsystem:latest
        kubectl-version: 'latest'
        namespace: default
        cluster-name: your-cluster-name
        resource-group: your-resource-group
        credentials: ${{ secrets.AZURE_CREDENTIALS }}

  notify:
    runs-on: ubuntu-latest
    needs: build
    if: failure()
    steps:
    - name: Send email notification
      uses: dawidd6/action-send-mail@v3  # Ensure you are using the latest version
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: ${{ secrets.SMTP_USERNAME }}
        password: ${{ secrets.SMTP_PASSWORD }}
        subject: Build Notification
        to: henryleungdemotest@gmail.com
        from: github-actions@gmail.com
        body: |
          Build Notification

          The build has completed successfully.

          **Repository**: ${{ github.repository }}
          **Branch**: ${{ github.ref }}
          **Commit**: ${{ github.sha }}
          **Commit Message**: ${{ github.event.head_commit.message }}
          **Author**: ${{ github.event.head_commit.author.name }}
          **Build URL**: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

          Please check the logs for more details.