name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Build with Maven
      run: mvn clean package

    - name: Build Docker image
      run: docker build -t your-dockerhub-username/frauddetectionsystem:latest .

    - name: Log in to Docker Hub
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Push Docker image
      run: docker push your-dockerhub-username/frauddetectionsystem:latest

    - name: Deploy to Kubernetes
      uses: azure/k8s-deploy@v1
      with:
        manifests: |
          deployment.yaml
          service.yaml
        images: |
          your-dockerhub-username/frauddetectionsystem:latest
        kubectl-version: 'latest'
        namespace: default
        cluster-name: your-cluster-name
        resource-group: your-resource-group
        credentials: ${{ secrets.AZURE_CREDENTIALS }}